### ISSUE TITLE
It’s possible to make telegram bot

### ISSUE THREAD

**Issue by moosergamer** [cyberboysumanjay/Torrent-Searcher#3]
Can you tell me .

**Comment by cyberboysumanjay** [comment]
Yes you can make telegram bot but you need to add proxy to send requests at that scale

You can use a live version here https://t.me/torrentsearcher_bot

**Comment by moosergamer** [comment]
I wanna build to my own host

**Comment by cyberboysumanjay** [comment]
You need to check live sites which offer scraping and use proxy to bypass limitations.
